name: lyriccist_server
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  grpc: ^3.2.3
  protos:
    path: ../protos

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
